import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { ArrowRight, Heart, Star, Tag } from "lucide-react";
import { getStoreBadgeClass } from "@/lib/cms-stores";
import { cn } from "@/lib/utils";
export function ProductDetailMeta({ product, content, }) {
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [_jsx("span", { className: cn("text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full", getStoreBadgeClass(product.store, content)), children: product.store }), _jsx("span", { className: "text-[10px] font-semibold text-muted-foreground bg-muted px-2.5 py-1 rounded-full", children: product.category })] }), _jsx("h1", { className: "mt-4 font-display font-extrabold text-2xl md:text-3xl leading-tight", children: product.name }), _jsxs("div", { className: "flex items-center gap-2 mt-3 text-sm text-muted-foreground", children: [_jsx(Star, { className: "size-4 fill-primary text-primary" }), _jsx("span", { className: "font-semibold text-foreground", children: product.rating.toFixed(1) }), _jsx("span", { children: "\u00B7 4.2k vendidos" })] }), _jsxs("div", { className: "mt-5 flex flex-wrap items-baseline gap-2 sm:gap-3", children: [_jsxs("span", { className: "font-display font-extrabold text-2xl sm:text-4xl text-primary", children: ["R$ ", product.price.toFixed(2).replace(".", ",")] }), _jsxs("span", { className: "text-base sm:text-lg text-muted-foreground line-through", children: ["R$ ", product.oldPrice.toFixed(2).replace(".", ",")] })] }), _jsxs("p", { className: "mt-2 text-sm font-semibold text-primary", children: ["Economize R$ ", (product.oldPrice - product.price).toFixed(2).replace(".", ",")] }), _jsx("p", { className: "mt-6 text-sm text-muted-foreground leading-relaxed", children: product.description })] }));
}
export function ProductDetailActions({ product, fav, onBuy, onToggleFavorite, }) {
    return (_jsxs("div", { className: "mt-8 flex flex-col sm:flex-row gap-3", children: [_jsxs("button", { type: "button", onClick: onBuy, className: "inline-flex flex-1 items-center justify-center gap-2 bg-gradient-cta text-primary-foreground rounded-2xl px-4 sm:px-6 py-3.5 text-xs sm:text-sm font-semibold shadow-glow hover:scale-[1.01] transition-transform text-center", children: [_jsxs("span", { className: "sm:hidden", children: ["Comprar \u00B7 ", product.store] }), _jsxs("span", { className: "hidden sm:inline", children: ["Comprar na ", product.store] }), _jsx(ArrowRight, { className: "size-4" })] }), _jsxs("button", { type: "button", onClick: onToggleFavorite, className: cn("inline-flex items-center justify-center gap-2 rounded-2xl px-6 py-3.5 text-sm font-semibold transition-colors", fav ? "bg-primary/10 text-primary" : "bg-muted hover:bg-accent text-foreground"), children: [_jsx(Heart, { className: cn("size-4", fav && "fill-primary") }), fav ? "Favoritado" : "Favoritar"] })] }));
}
export function ProductAffiliateNote({ storeName }) {
    return (_jsxs("div", { className: "mt-6 flex items-start gap-3 bg-surface rounded-2xl p-4 shadow-soft", children: [_jsx("div", { className: "size-9 rounded-xl bg-muted grid place-items-center shrink-0", children: _jsx(Tag, { className: "size-4 text-primary" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs font-semibold", children: "Link de afiliado seguro" }), _jsxs("p", { className: "text-[11px] text-muted-foreground mt-0.5", children: ["Ao comprar, voc\u00EA ser\u00E1 redirecionado para ", storeName, " pelo link curado do AfiliaHub."] })] })] }));
}
