/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MaisclicadosRouteImport } from './routes/maisclicados'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CashbackRouteImport } from './routes/cashback'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaIndexRouteImport } from './routes/conta/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutoProductIdRouteImport } from './routes/produto.$productId'
import { Route as ContaVerificarRouteImport } from './routes/conta/verificar'
import { Route as ContaRegistarRouteImport } from './routes/conta/registar'
import { Route as ContaEntrarRouteImport } from './routes/conta/entrar'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminConfigApisRouteImport } from './routes/admin/config-apis'
import { Route as AdminEditSectionRouteImport } from './routes/admin/edit.$section'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
})
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
})
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
})
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
})
const MaisclicadosRoute = MaisclicadosRouteImport.update({
  id: '/maisclicados',
  path: '/maisclicados',
  getParentRoute: () => rootRouteImport,
})
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
})
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
})
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
})
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
})
const CashbackRoute = CashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => rootRouteImport,
})
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/conta/',
  path: '/conta/',
  getParentRoute: () => rootRouteImport,
})
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
})
const ProdutoProductIdRoute = ProdutoProductIdRouteImport.update({
  id: '/produto/$productId',
  path: '/produto/$productId',
  getParentRoute: () => rootRouteImport,
})
const ContaVerificarRoute = ContaVerificarRouteImport.update({
  id: '/conta/verificar',
  path: '/conta/verificar',
  getParentRoute: () => rootRouteImport,
})
const ContaRegistarRoute = ContaRegistarRouteImport.update({
  id: '/conta/registar',
  path: '/conta/registar',
  getParentRoute: () => rootRouteImport,
})
const ContaEntrarRoute = ContaEntrarRouteImport.update({
  id: '/conta/entrar',
  path: '/conta/entrar',
  getParentRoute: () => rootRouteImport,
})
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
})
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
})
const AdminConfigApisRoute = AdminConfigApisRouteImport.update({
  id: '/admin/config-apis',
  path: '/admin/config-apis',
  getParentRoute: () => rootRouteImport,
})
const AdminEditSectionRoute = AdminEditSectionRouteImport.update({
  id: '/admin/edit/$section',
  path: '/admin/edit/$section',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CashbackRoute: CashbackRoute,
  CategoriasRoute: CategoriasRoute,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  CuponsRoute: CuponsRoute,
  MaisclicadosRoute: MaisclicadosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminConfigApisRoute: AdminConfigApisRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  ContaEntrarRoute: ContaEntrarRoute,
  ContaRegistarRoute: ContaRegistarRoute,
  ContaVerificarRoute: ContaVerificarRoute,
  ProdutoProductIdRoute: ProdutoProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContaIndexRoute: ContaIndexRoute,
  AdminEditSectionRoute: AdminEditSectionRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
