/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MaisclicadosRouteImport } from './routes/maisclicados'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CashbackRouteImport } from './routes/cashback'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaIndexRouteImport } from './routes/conta/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutoProductIdRouteImport } from './routes/produto.$productId'
import { Route as ContaVerificarRouteImport } from './routes/conta/verificar'
import { Route as ContaRegistarRouteImport } from './routes/conta/registar'
import { Route as ContaEntrarRouteImport } from './routes/conta/entrar'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminConfigApisRouteImport } from './routes/admin/config-apis'
import { Route as AdminEditSectionRouteImport } from './routes/admin/edit.$section'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisclicadosRoute = MaisclicadosRouteImport.update({
  id: '/maisclicados',
  path: '/maisclicados',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbackRoute = CashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/conta/',
  path: '/conta/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoProductIdRoute = ProdutoProductIdRouteImport.update({
  id: '/produto/$productId',
  path: '/produto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaVerificarRoute = ContaVerificarRouteImport.update({
  id: '/conta/verificar',
  path: '/conta/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRegistarRoute = ContaRegistarRouteImport.update({
  id: '/conta/registar',
  path: '/conta/registar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaEntrarRoute = ContaEntrarRouteImport.update({
  id: '/conta/entrar',
  path: '/conta/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigApisRoute = AdminConfigApisRouteImport.update({
  id: '/admin/config-apis',
  path: '/admin/config-apis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditSectionRoute = AdminEditSectionRouteImport.update({
  id: '/admin/edit/$section',
  path: '/admin/edit/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cashback': typeof CashbackRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/cupons': typeof CuponsRoute
  '/maisclicados': typeof MaisclicadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/config-apis': typeof AdminConfigApisRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/conta/entrar': typeof ContaEntrarRoute
  '/conta/registar': typeof ContaRegistarRoute
  '/conta/verificar': typeof ContaVerificarRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/admin/edit/$section': typeof AdminEditSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cashback': typeof CashbackRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/cupons': typeof CuponsRoute
  '/maisclicados': typeof MaisclicadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/config-apis': typeof AdminConfigApisRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/conta/entrar': typeof ContaEntrarRoute
  '/conta/registar': typeof ContaRegistarRoute
  '/conta/verificar': typeof ContaVerificarRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/conta': typeof ContaIndexRoute
  '/admin/edit/$section': typeof AdminEditSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cashback': typeof CashbackRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/cupons': typeof CuponsRoute
  '/maisclicados': typeof MaisclicadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/config-apis': typeof AdminConfigApisRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/conta/entrar': typeof ContaEntrarRoute
  '/conta/registar': typeof ContaRegistarRoute
  '/conta/verificar': typeof ContaVerificarRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/admin/edit/$section': typeof AdminEditSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cashback'
    | '/categorias'
    | '/contato'
    | '/cookies'
    | '/cupons'
    | '/maisclicados'
    | '/privacidade'
    | '/produtos'
    | '/sobre'
    | '/termos'
    | '/admin/config-apis'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/conta/entrar'
    | '/conta/registar'
    | '/conta/verificar'
    | '/produto/$productId'
    | '/admin/'
    | '/conta/'
    | '/admin/edit/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cashback'
    | '/categorias'
    | '/contato'
    | '/cookies'
    | '/cupons'
    | '/maisclicados'
    | '/privacidade'
    | '/produtos'
    | '/sobre'
    | '/termos'
    | '/admin/config-apis'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/conta/entrar'
    | '/conta/registar'
    | '/conta/verificar'
    | '/produto/$productId'
    | '/admin'
    | '/conta'
    | '/admin/edit/$section'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cashback'
    | '/categorias'
    | '/contato'
    | '/cookies'
    | '/cupons'
    | '/maisclicados'
    | '/privacidade'
    | '/produtos'
    | '/sobre'
    | '/termos'
    | '/admin/config-apis'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/conta/entrar'
    | '/conta/registar'
    | '/conta/verificar'
    | '/produto/$productId'
    | '/admin/'
    | '/conta/'
    | '/admin/edit/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CashbackRoute: typeof CashbackRoute
  CategoriasRoute: typeof CategoriasRoute
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  CuponsRoute: typeof CuponsRoute
  MaisclicadosRoute: typeof MaisclicadosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AdminConfigApisRoute: typeof AdminConfigApisRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ContaEntrarRoute: typeof ContaEntrarRoute
  ContaRegistarRoute: typeof ContaRegistarRoute
  ContaVerificarRoute: typeof ContaVerificarRoute
  ProdutoProductIdRoute: typeof ProdutoProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContaIndexRoute: typeof ContaIndexRoute
  AdminEditSectionRoute: typeof AdminEditSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maisclicados': {
      id: '/maisclicados'
      path: '/maisclicados'
      fullPath: '/maisclicados'
      preLoaderRoute: typeof MaisclicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons': {
      id: '/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof CuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashback': {
      id: '/cashback'
      path: '/cashback'
      fullPath: '/cashback'
      preLoaderRoute: typeof CashbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/': {
      id: '/conta/'
      path: '/conta'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$productId': {
      id: '/produto/$productId'
      path: '/produto/$productId'
      fullPath: '/produto/$productId'
      preLoaderRoute: typeof ProdutoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/verificar': {
      id: '/conta/verificar'
      path: '/conta/verificar'
      fullPath: '/conta/verificar'
      preLoaderRoute: typeof ContaVerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/registar': {
      id: '/conta/registar'
      path: '/conta/registar'
      fullPath: '/conta/registar'
      preLoaderRoute: typeof ContaRegistarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/entrar': {
      id: '/conta/entrar'
      path: '/conta/entrar'
      fullPath: '/conta/entrar'
      preLoaderRoute: typeof ContaEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config-apis': {
      id: '/admin/config-apis'
      path: '/admin/config-apis'
      fullPath: '/admin/config-apis'
      preLoaderRoute: typeof AdminConfigApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit/$section': {
      id: '/admin/edit/$section'
      path: '/admin/edit/$section'
      fullPath: '/admin/edit/$section'
      preLoaderRoute: typeof AdminEditSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CashbackRoute: CashbackRoute,
  CategoriasRoute: CategoriasRoute,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  CuponsRoute: CuponsRoute,
  MaisclicadosRoute: MaisclicadosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminConfigApisRoute: AdminConfigApisRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  ContaEntrarRoute: ContaEntrarRoute,
  ContaRegistarRoute: ContaRegistarRoute,
  ContaVerificarRoute: ContaVerificarRoute,
  ProdutoProductIdRoute: ProdutoProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContaIndexRoute: ContaIndexRoute,
  AdminEditSectionRoute: AdminEditSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
